### ISSUE TITLE
Unable to build with PHP+Suhosin

### ISSUE THREAD

**Issue by faf** [dmcdaniel12/mibew_slack#1]
We use Suhosin for PHP to enhance the security.

If I try to run `gulp` to build the plugin, I got the error:

> [15:33:03]  Attempting to download composer to system temp directory...               
> 
> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> Error: Some settings on your machine make Composer unable to work properly.
> Make sure that you fix the issues listed below and run this script again:
> 
> The suhosin.executor.include.whitelist setting is incorrect.
> Add the following to the end of your `php.ini` or suhosin.ini (Example path [for Debian]: /etc/php5/cli/conf.d/suhosin.ini):
>     suhosin.executor.include.whitelist = phar 
> 

We've already encountered this issue before, that's why we use [this](https://github.com/Mibew/mibew/blob/master/src/gulpfile.js#L44) in the `gulpfile.js` for Mibew Messenger itself.

**Comment by dmcdaniel12** [comment]
Thanks. Will get this fixed tonight.
