### ISSUE TITLE
Unable to build: composer.json missed

### ISSUE THREAD

**Issue by faf** [dmcdaniel12/mibew_slack#4]
At the time if I try to run gulp to build the plugin, I got the error:

> module.js:471
>     throw err;
>     ^
> 
> Error: Cannot find module './composer.json'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/tmp/mibew_slack/gulpfile.js:15:18)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)

**Comment by dmcdaniel12** [comment]
Thanks. Will get this fixed tonight @faf

**Comment by dmcdaniel12** [comment]
@faf Can you try now? composer.json is now included. If it builds for you, I will go ahead and close this ticket. If not, I will install a test env w/ suhosin.

**Comment by faf** [comment]
yes, now it is possible to build the plugin. but... here comes the issue #5.
