### ISSUE TITLE
Problem with rebuilding the plugin

### ISSUE THREAD

**Issue by faf** [dmcdaniel12/mibew_slack#6]
The plugin could be built smoothly:

> $ gulp
> [08:41:02] Using gulpfile ~/reps/mibew_slack/gulpfile.js
> [08:41:02] Starting 'get-composer'...
> [08:41:02] Starting 'prepare-release'...
> [08:41:02] Finished 'prepare-release' after 137 ms
> [08:41:04] Finished 'get-composer' after 2.3 s
> [08:41:04] Starting 'composer-install'...
> [08:41:05] Finished 'composer-install' after 632 ms
> [08:41:05] Starting 'default'...
> [08:41:05] Finished 'default' after 2.67 μs

But if one try to rebuild it, there comes an error:

> $ gulp
> [08:41:08] Using gulpfile ~/reps/mibew_slack/gulpfile.js
> [08:41:08] Starting 'get-composer'...
> [08:41:08] Finished 'get-composer' after 144 μs
> [08:41:08] Starting 'composer-install'...
> [08:41:08] Starting 'prepare-release'...
> [08:41:08] Finished 'composer-install' after 174 ms
> [08:41:09] 'prepare-release' errored after 541 ms
> [08:41:09] Error: EACCES: permission denied, open '/home/webadmin/reps/mibew_slack/release/slack-1.0.0.tar.gz'
>     at Error (native)

Seems like the cause is wrong permissions: 

> $ ls -l release/
> -r---w---- 1 webadmin webadmin 5552 фев  8 08:41 slack-1.0.0.tar.gz
> -r---w---- 1 webadmin webadmin 6411 фев  8 08:41 slack-1.0.0.zip

**Comment by faf** [comment]
Here is the fix: #7

**Comment by dmcdaniel12** [comment]
Thanks. Merged in and closed.
