### ISSUE TITLE
FR: Localization

### ISSUE THREAD

**Issue by faf** [dmcdaniel12/mibew_slack#8]
At the time the notification message is hardcoded.

**Comment by dmcdaniel12** [comment]
Are you talking about the message within the plugin? If so, I can change that. Just want to make sure I am doing the right thing. I assume you mean this:

$client->send(date('Y-m-d H:i:s') . ' - You have a new user waiting for a response. Username: ' . $args['thread']->userName);

**Comment by faf** [comment]
Yes, I meant that sentence. Actually, there are no other strings that could be visible to end user. :)

**Comment by dmcdaniel12** [comment]
@faf okay perfect. I will fix that tonight and push another release.

**Comment by dmcdaniel12** [comment]
Completed.
